### ISSUE TITLE
Duplicate?

### ISSUE THREAD

**Issue by shinnn** [jonschlinkert/stringify-author#1]
https://github.com/sindresorhus/somebody

**Comment by jonschlinkert** [comment]
Mine was created months before:
- https://github.com/jonschlinkert/parse-authors/commit/e8f4b1107f66f07749ad97329409287ad384b18f 
- https://github.com/assemble/verb/blob/1a3639aad27afce6c70158a61e9b2c9fbe855fe8/lib/tags/authors.js
- https://github.com/assemble/verb/blob/1a3639aad27afce6c70158a61e9b2c9fbe855fe8/lib/tags/getAuthors.js

all I did was break out code I already had.

**Comment by shinnn** [comment]
Ah, sorry I overlooked parse-authors project.

**Comment by jonschlinkert** [comment]
that's okay :) it seems to happen to me a lot lol

**Comment by jonschlinkert** [comment]
jk, I think this is just going to happen sometimes when highly productive developers are working on similar tools sometimes. IMHO the libs have material differences, I couldn't use somebody on my projects, it doesn't cover enough use cases.
